Writing first spec
Porters/matching-pro-recommendation-api pull request #1
Opened 2021-06-30 02:27 UTC by edwaltz89

Writing first spec about recommendation api

2021-06-30 04:37 UTC, ChihyungPark commented on openapi-assist.yml
> +      RecommendationsOutput:
everything seems okay, 
but here the output of recommendation seems different from the type in content. 
If it is okay, I'm okay

2021-06-30 04:56 UTC, edwaltz89 commented on openapi-assist.yml
> +      RecommendationsOutput:
Maybe It's okay. because as feature spec in ticket, pagination with button click is just call 1 record.
so I think It is okay if we don't have to wrapping with array
I'll fix the put method's RecommendationsInput format and re-request review. thx 4 your comment!

2021-06-30 05:06 UTC, ChihyungPark approved these changes

2021-06-30 05:15 UTC, edwaltz89 commented on openapi-assist.yml
> +      RecommedationsInput:
@ChihyungPark 
Fixed input schema. thx!

2021-06-30 05:25 UTC, SeraphicRav requested changes
Questions:
- there is concept of index which only exists in the get endpoint. How do you know the current index ?
- what happens when recommendations get scouted or is marked as not-good ? The index might skip some recommendations

2021-06-30 05:25 UTC, SeraphicRav commented on openapi-assist.yml
> +    patch:
Patching usually asks for a path parameter element representing the id of the updated thing
Maybe having the path /recommendations/{sourceId}/resume/{resumeId}/job/{jobId}

With
```json
{
  "status": "boolean"
}
```

Would be more restlike

2021-06-30 05:25 UTC, SeraphicRav commented on openapi-assist.yml
> +      RecommendationsOutput:
I think we should use the same input/output format to make typing and manipulation easier. You can reuse schemas in OpenAPI too.

2021-06-30 06:43 UTC, edwaltz89 commented
> Questions:
> 
> * there is concept of index which only exists in the get endpoint. How do you know the current index ?
> * what happens when recommendations get scouted or is marked as not-good ? The index might skip some recommendations

Answers:

1. there is concept of index which only exists in the get endpoint. How do you know the current index ?
I think that recommendation-api don't have to know current index.
I just expect to receive index from web in order by clicking button and api is just response by index record

2. what happens when recommendations get scouted or is marked as not-good ? The index might skip some recommendations
When recommendation is scouted or marked not good, I expect the status flag is changed and by changed flag, recommendation changed flag is not listed

2021-07-01 02:14 UTC, edwaltz89 commented on openapi-assist.yml
> +    patch:
@SeraphicRav 
Changed parameter from query to path and remove query string in patch method

2021-07-01 06:39 UTC, edwaltz89 commented
Added fix details after last reviews:
1. Update name and schema of recommendation item
2. Changed parameter from query to path and remove query string in patch method
3. Add the index field in GET method response

2021-07-01 07:44 UTC, SeraphicRav requested changes

2021-07-01 07:44 UTC, SeraphicRav commented on openapi-assist.yml
> +        500:
Please add 404 in the case that there is no recommendation left

2021-07-01 07:44 UTC, SeraphicRav commented on openapi-assist.yml
> +          type: number
Please add an index

2021-07-01 07:44 UTC, SeraphicRav commented on openapi-assist.yml
> +      required: true
It should be optional.

When doing the first call, the API user does not have any idea about what is the latest index. So when it is not provided, the latest recommendations should be provided

Otherwise this number should be the current position

2021-07-01 07:44 UTC, SeraphicRav commented on openapi-assist.yml
> +        type: number
Let us add a new query parameter: direction which can be either next or previous so that we know if we need to look for a value smaller or bigger than index

2021-07-01 07:44 UTC, SeraphicRav commented on openapi-assist.yml
> +  /recommendation:
Let us use recommendationS for the path as we are using plural in core and web by default

2021-07-01 07:44 UTC, SeraphicRav commented on openapi-assist.yml
> +          type: number
I think a string status would be more readable. Let us also name it status to make it smaller

2021-07-01 08:34 UTC, edwaltz89 commented
Added fix details after last reviews:

Update index parameter to optional
Add direction parameter
Update name in path from recommendation to recommendations

2021-07-01 08:45 UTC, SeraphicRav requested changes

2021-07-01 08:45 UTC, SeraphicRav commented on openapi-assist.yml
> +        status:
Let us use string for status

2021-07-01 08:45 UTC, SeraphicRav commented on openapi-assist.yml
> +      description: page direction ( prev | next )
Let us use the full world previous

2021-07-01 08:45 UTC, SeraphicRav commented on openapi-assist.yml
> +      description: Current index to recommendation pagination (Using with pageDirection)
pageDirection became direction

2021-07-01 08:45 UTC, SeraphicRav commented on openapi-assist.yml
> +      description: page direction ( prev | next )
You can use an enum to limit the possible values

2021-07-01 08:47 UTC, SeraphicRav requested changes

2021-07-01 08:47 UTC, SeraphicRav commented on openapi-assist.yml
> +      required: true
direction should not be required, it should be required when you provide an index (Don't know if OpenAPI allows this kind of dependency)

2021-07-01 08:59 UTC, SeraphicRav approved these changes

2021-07-02 00:07 UTC, ChihyungPark approved these changes

2021-07-02 00:51 UTC, merged